from .LTX2EasyPromptLD import (
    NODE_CLASS_MAPPINGS        as _TEXT_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _TEXT_NAMES,
)
from .LTX2VisionEasyPromptLD import (
    NODE_CLASS_MAPPINGS        as _VISION_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _VISION_NAMES,
)

NODE_CLASS_MAPPINGS = {
    **_TEXT_CLASSES,
    **_VISION_CLASSES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **_TEXT_NAMES,
    **_VISION_NAMES,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
